# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five_stars', models.PositiveIntegerField()),
                ('four_stars', models.PositiveIntegerField()),
                ('three_stars', models.PositiveIntegerField()),
                ('two_stars', models.PositiveIntegerField()),
                ('one_stars', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
            ],
        ),
    ]
