# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20170824_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='five_stars',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='four_stars',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='one_stars',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='three_stars',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='two_stars',
        ),
        migrations.AddField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
